### ISSUE TITLE
API reference with JSDocs

### ISSUE THREAD

**Issue by MichalLytek** [19majkel94/type-graphql#17]
- [ ] create JSDoc for all decorators and public interfaces/functions/etc.
- [ ] create docs section with API Reference (text from JSDoc, samples from item signature)
- [ ] investigate usage of [TypeDoc](https://github.com/TypeStrong/typedoc)
- [ ] configure website to show API reference

**Comment by kurtzilla** [comment]
Not sure this issue is solved via #262 
Is there a listing of available decorators anywhere? Seems the only way to get info on a decorator is to already know that it exists. Pardon my ignorance - but trying to figure out how to use the feature.

**Comment by tradical-allstripes** [comment]
Any update on this? API Reference Documentation has always been key for me, and, as much as I love this project, this may influence our decision about whether to use it.

In the meantime, it would be extremely helpful if you could provide either some links to what you think are the most important definitions, or a strategy to make locating them easier.

**Comment by MichalLytek** [comment]
The TS definition files are well maintained and acts as an API reference if you forgot about possible decorators options.

TypeGraphQL is more frameworkish so the API reference docs page for e.g. `@Resolver` decorator could only link to the normal docs page when the resolvers, classes, types, etc. are described.

It's not a library where you can simply describe each function input and output, so there's less demand for such API reference docs page. I have more important tasks and features to do, so it's not on top of my priority list for now.

If anyone from the community want to help and contribute, please feel free to open a PR 😉

**Comment by tradical-allstripes** [comment]
Ok, that's understandable. Thank you for the reply!

**Comment by MichalLytek** [comment]
If someone is looking for something more user-friendly than jumping through typescript definitions in IDE, you can try to use a tool called Paka 😉 
https://www.paka.dev/npm/type-graphql

**Comment by tradical-allstripes** [comment]
ah, this is super cool! Thank you!
