### ISSUE TITLE
Error when using GraphQLJSON

### ISSUE THREAD

**Issue by egges** [19majkel94/type-graphql#188]
The latest version (0.15.0) seems to have issues with custom scalars such as the JSON type provided by the GraphQLJSON package (graphql-type-json).

Here is a basic example of what I'd like to do:
```typescript
import { ObjectType, Field } from "type-graphql";
import GraphQLJSON = require("graphql-type-json");

@ObjectType()
export default class MyData {

    @Field(type => GraphQLJSON)
    public jsonData: any;
}
```

This results in the following error: "Error: Cannot determine GraphQL input type for jsonData".

When I go back to the previous version (0.14.0) and GraphQL version 0.13.2, the error disappears and my code works again.

**Environment:**
 - OS: Mac, Windows
 - Node: 10.12.0
 - Package version: 0.15.0
 - TypeScript version: 3.1.4

**Comment by 19majkel94** [comment]
According to the code:
https://github.com/taion/graphql-type-json/blob/5790abc351b3007dc9dc98ccf35e9ea72ed7ba91/src/index.js#L37

You should do:
`import GraphQLJSON = require("graphql-type-json")`;

But as I've tried in reproduction repo:
https://gitlab.com/esindger/tgql-scalar-example

You should do:
`import * as GraphQLJSON from "graphql-type-json";`
instead of:
`import GraphQLJSON from "graphql-type-json";`

Then it works 😃 
![code_2018-10-31_18-35-48](https://user-images.githubusercontent.com/10618781/47807322-10892600-dd3c-11e8-92ea-63765c25edf8.png)

**Comment by egges** [comment]
Thanks for your response! After making this change it works :).

**Comment by davewasmer** [comment]
I'm running into this issue myself, and the suggested fix doesn't seem to help.

I traced it down and it seems like this check is failing:

https://github.com/19majkel94/type-graphql/blob/63d4858f882625ef9bebcf2ce5fa0150662a93e6/src/helpers/types.ts#L18

It appears that there's two different copies of `GraphQLScalarType` being loaded - one by the GraphQLJSON lib and one by TypeGraphQL. I can probably figure out a workaround for this particular case, but long term it seems like it might be better to avoid relying on `instanceof` checks like that unless we can be certain the object being tested was created internally in TypeGraphQL (and therefore will have the correct prototype chain).

In another thread one idea mentioned was to simply export `GraphQLScalarType` from TypeGraphQL so consuming apps could use it to properly construct an instance with the necessary prototype chain, but I don't think that would work here either, since the GraphQLJSON library is the one using `GraphQLScalarType`.

**Comment by 19majkel94** [comment]
@davewasmer 
That's the main reason why I decided to switch to peer-dependency. This issue should be fixed in next release.

**Comment by darkmantle** [comment]
Have tried `npm dedupe` but still getting this error. Any ideas? It's completely broken my API now.

**Comment by 19majkel94** [comment]
`npm i type-graphql@next`
https://19majkel94.github.io/type-graphql/docs/next/installation.html

**Comment by darkmantle** [comment]
That fixed some of it, but not completely. Not sure if it is the same problem, but I get the same error on:

```ts
@Mutation(returns => ApiError)
    async recordConsent(@Arg("consents", type => GraphQLJSON) consents: UserConsent[]) {
        const body = await FetchConfig.fetch("user-record-consent", { consents });
        return body;
    }
```

**Comment by 19majkel94** [comment]
@darkmantle Please create a repository with reproducible code example.

**Comment by darkmantle** [comment]
https://github.com/darkmantle/type-graphql-bug

**Comment by 19majkel94** [comment]
@darkmantle 

Setting:
```js
  "allowSyntheticDefaultImports": true,
  "esModuleInterop": true,
```
Means you should use default import:
```ts
import GraphQLJSON from "graphql-type-json";
```

**Comment by darkmantle** [comment]
Thank you! I actually changed it everywhere but that one place. Rookie error.

**Comment by goldcaddy77** [comment]
The `type instanceof GraphQLScalarType` checks also seems to cause issues if you `yarn link` into another project that has a different version of `graphql` installed.  Would it make sense to use `type.constructor.name` checks here to guard against this?

**Comment by 19majkel94** [comment]
No, you need to have only one version of `graphql-js` in your project, otherwise you will have the "another realm" error.

**Comment by manuelalcantara52** [comment]
I have the same problem with this library:
https://www.npmjs.com/package/graphql-custom-types

**Comment by himharsh1997** [comment]
```
   import { GraphQLJSONObject } from 'graphql-type-json';
   import { Field, InputType, Int, ObjectType } from 'type-graphql';
   import { Entity, ManyToOne, JoinTable, Column } from 'typeorm';
 ...other libraries
  @ObjectType('DemoModelType') 
  @InputType('DemoModelInput')
  @Entity()
  export class DemoModel {
... columns before it
    @Field(() => GraphQLJSONObject || null, { nullable: true })
    @prop({ unique: false, required: false })
    @Column()
    public myKey!: object | null;
}
```

**Comment by vjpr** [comment]
NOTE: This can also happen if you are using two different versions of `graphql`.

Why? If you trace the error you find that it checks if the type is a scalar by checking `instanceof graphql.GraphQLScalarType`. This will fail if the scalar was not created using the same `graphql` instance.

```
function convertTypeIfScalar(type) {
    if (type instanceof graphql_1.GraphQLScalarType) {
        return type;
    }
    const scalarMap = build_context_1.BuildContext.scalarsMaps.find(it => it.type === type);
    if (scalarMap) {
        return scalarMap.scalar;
    }
    switch (type) {
        case String:
            return graphql_1.GraphQLString;
        case Boolean:
            return graphql_1.GraphQLBoolean;
        case Number:
            return graphql_1.GraphQLFloat;
        case Date:
            return build_context_1.BuildContext.dateScalarMode === "isoDate" ? isodate_1.GraphQLISODateTime : timestamp_1.GraphQLTimestamp;
        default:
            return undefined;
    }
}
```

**Comment by MichalLytek** [comment]
> Would be nice if type-graphql could provide some kind of check for us...

Do you know how `type-graphql` could check that? 🤔

**Comment by ceddybi** [comment]
> "another realm" error.

I just died when you said another "another realm" 😂🤣🤣
