### ISSUE TITLE
@FieldResolver is not working, not even called

### ISSUE THREAD

**Issue by hxdef2517** [19majkel94/type-graphql#309]
I'm trying to implement FieldResolver inside resolver class, but it seems it never called, while entity resolver works ok.

**tsconfig.json**

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2016",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./"
  },
  "exclude": ["node_modules"]
}

```

**Entity:** 

```ts
const tableOptions: IDefineOptions = {
    timestamp: true,
    tableName: 'notifications'
} as IDefineOptions;

@Table(tableOptions)
@ObjectType()
export class Notifications extends Model<Notifications> {

    @Column({
        type: DataType.INTEGER(11),
        autoIncrement: true,
        allowNull: false,
        unique: true,
        primaryKey: true
    })
    @Field(type => ID)
    public id: number;

    @Column({
        type: DataType.STRING(255),
        allowNull: false,
        field: 'title'
    })
    @Field()
    public title: string;

    @Column({
        type: DataType.TEXT,
        allowNull: false,
        field: 'body'
    })
    @Field()
    public body: string;


    @Field(type => Int, { nullable: true })
    public isRead?: number;

// This way its working [!]
    /* @Field(type => Float, { nullable: true })
    isRead(): number | null {
        console.log('isRead Resolver');
        return <number> this.dataValues['isRead'];
    } */

    @CreatedAt public createdAt: Date;
    @UpdatedAt public updatedAt: Date;
}
```

**Resolver:** 

```ts
@Resolver(of => Notifications)
export class NotificationsResolver {

    constructor(private readonly notificationsService: NotificationsService) {}

    @Query(returns => [Notifications])
    async getLatestNotifications(
        @Context('user') user
        ) {        
        let notifications = await this.notificationsService.getLatestNotifications(user);        
        return notifications;
    }

    // Never called, not working
    @FieldResolver(returns => Int, { nullable: true })
    isRead(@Root() notification: Notifications) {
        console.log('FieldResolver isRead:', notification);
        return 33;
    }
```

**Comment by 19majkel94** [comment]
The code looks correct, so the problem might be somewhere else in your code.

Please try to reproduce it without `NotificationsService` or `extends Model<Notifications>` and create a repository with a minimal reproducible example.

**Comment by hxdef2517** [comment]
@19majkel94 well extends Model<Notifications> its the default sequelize typescript entity definition. 
Will prepare small project for you to try

**Comment by hxdef2517** [comment]
@19majkel94 actually can I ask you something, if my entity doesn't have a custom field, by right this field should be resolved using @FieldResolver or @Field ? Is it a bad practice to cast entity results to custom response like NotificationsResponse below with extra entities ? For example

```
@ObjectType()
export class NotificationsResponse {
    constructor(notification: Notifications) {
        this.id = notification.dataValues.id;
        this.title = notification.dataValues.title;
        this.body = notification.dataValues.body;
        this.isRead = notification.dataValues['isRead'];
    } 

    @Field()
    id: number;

    @Field()
    title: string;

    @Field()
    body: string;

    @Field({ nullable: true })
    isRead: number;
}
```

**Comment by 19majkel94** [comment]
> by right this field should be resolved using @FieldResolver or @field 

It goes this way:
1. executing `@FieldResolver` if exist
2. if not, executing `@Field` method if exist
3. if not, reading the property value of the object

And you can't at once have a field method/getter and a field resolver.

**Comment by sammysaglam** [comment]
im stuck on the below, is there a way to do this?

```
@ObjectType()
export class User {
    @Field(type => ID)
    email: string;

    @Field(type => [Post])
    posts(@Arg('since', { nullable: true }) since?: string): Post[];
}
```
But now the above requires a method since it has arguments.
And because of `you can't at once have a field method/getter and a field resolver.` I am unable to add a Field resolver.

**Comment by 19majkel94** [comment]
You can't have a field method:
```ts
@ObjectType()
export class User {
    @Field(type => [Post])
    posts(@Arg('since', { nullable: true }) since?: string): Post[] {
		return [];
    }
}
```
And field resolver:
```ts
@Resolver(of => User)
export class UserResolver {
    @FieldResolver(returns => [Post])
    posts(@Root() user: User, @Arg('since', { nullable: true }) since?: string) {
        return [];
    }
}
```
Defined for the same field at the same time 😉 

> Note that if a field name of a field resolver doesn't exist in the resolver object type, it will create a field in the schema with this name. This feature is useful when the field is purely calculable (eg. averageRating from ratings array) and to avoid polluting the class signature.

https://typegraphql.ml/docs/resolvers.html#field-resolvers

**Comment by sammysaglam** [comment]
@19majkel94 makes sense, thanks!

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by hxdef2517** [comment]
Issue solved in latest version

**Comment by tommymarshall** [comment]
For sequelize-typescript, as the above example is using, dropping the @Field on the Model still doesn't call the @FieldResolver method if we're doing something like the below pseudo-code:
```js
@Table()
@ObjectType()
class Project {...}

@Resolver
class ProjectResolver {
  @FieldResolver
  public async options(){ return 'some promise that resolves to hi'; }
}

// in another resolver...
const project = Project.findByPk(1)
const options = await project.options
console.log(options) // output is `undefined`

// what does work is...
@Table()
@ObjectType()
class Project {
  get options() {
    return 'hi'; // can't be a promise... unless we wrap it with a anonymous async function
  }
}
// then the below does work
const options = await project.options
console.log(options) // output is `hi`
```

Perhaps this belongs under the sequelize-typescript repo, but this feels like a common scenario that others would have encountered and been confused by :)
